---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(modelr)
library(GGally)
```

```{r}
king <- read_csv("data/kc_house_data.csv")
glimpse(king)
summary(king)
```

```{r}
king_trim <- king %>%
  mutate(waterfront = ifelse(waterfront == 1, TRUE, FALSE),
         renovated = ifelse(yr_renovated == 0, FALSE, TRUE),
         condition = as.character(recode(condition,
                                         "1" = "Poor",
                                         "2" = "Fair",
                                         "3" = "Average",
                                         "4" = "Good", 
                                         "5" = "Very Good")),
         grade = as.factor(grade)) %>%
  select(-c("date", "id", "sqft_living15", "sqft_lot15", "zipcode", "yr_renovated")) 
```

```{r}
alias_model <- lm(price ~ ., data = king_trim)
alias(alias_model)
```

```{r}
king_trim <- king_trim %>%
  select(-"sqft_living")
```

```{r}
houses_tidy_numeric <- king_trim %>%
  select_if(is.numeric)

houses_tidy_nonnumeric <- king_trim %>%
  select_if(function(x) !is.numeric(x))

houses_tidy_nonnumeric$price <- king_trim$price

ggpairs(houses_tidy_numeric)
```

```{r}
ggpairs(houses_tidy_nonnumeric)
```


```{r}
mod1a <- lm(price ~ grade, data = king_trim)
summary(mod1a)
```

```{r}
mod1b <- lm(price ~ waterfront, data = king_trim)
summary(mod1b)
```

