---
title: "R Notebook"
output: html_notebook
---
2.2.1
```{r}
x <- 2

if(x){
  print(x * 15 + 4)
}
```

2.2.2
```{r}
bird <- "5"

if(bird == "goose" |
   bird == "duck" |
   bird == " pigeon"){
  print("bird")
}else{
  print("not a bird")
}
```

2.2.3
```{r}
y <- "d"

if(class(y) != "numeric"){
  print("Invalid input")
}else{
  print(y * 10)
}
```

2.3.1
```{r}
sizes <- c(13, 15, 10, 8, 22)

ifelse(sizes > 10, "Big", "Small")
```

2.3.2
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")

dplyr::recode(fruit, "apple" = "alpaca", "banana" = "bonobo", "cherry" = "chipmunk")

```

2.3.3
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)

dplyr::case_when(
  wife_age > husband_age ~ "Wife older",
  wife_age < husband_age ~ "Husband older",
  wife_age == husband_age ~ "Same age"
)

```

2.4.1
```{r}
my_list <- list(
  4,
  "apple",
  10.5,
  c("is", "an", "apple"),
  "apple",
  c("i", "like", "apples"),
  8
)
```

```{r}
for (item in my_list) {
  if(class(item) == "character"){
    print(item)
  }
}
```

2.4.2
```{r}
for (item in my_list) {
  if(class(item) == "character" &
     length(item) > 1){
    pasted <- paste(item)
    print(pasted)
  }
}

```






















